const mongoose = require('mongoose');

// ============================================================
// APPLICATION SCHEMA
// Purpose: Define the structure of an Application document in MongoDB
// Collection: applications
// Features: Job/internship application tracking, status pipeline,
//           networking contacts, follow-up reminders, resume linking
// ============================================================
const applicationSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link the application to the user who created it
     * Fields: userId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Job Info
     * Purpose: Store details about the position being applied to
     * Fields: company, position, location, jobUrl
     */
    company: {
        type: String,
        required: true,
    },
    position: {
        type: String,
        required: true,
    },
    location: {
        type: String,
    },
    jobUrl: {
        type: String,
    },

    /**
     * Status Pipeline
     * Purpose: Track where the application is in the hiring process
     * Fields: status
     */
    status: {
        type: String,
        enum: ['draft', 'applied', 'interview', 'offer', 'rejected', 'withdrawn'],
        default: 'draft',
        index: true,
    },

    /**
     * Timeline
     * Purpose: Track key dates throughout the application process
     * Fields: appliedAt, interviewDates, offerReceivedAt, deadlineDate
     */
    appliedAt: {
        type: Date,
    },
    interviewDates: [{
        type: Date,
    }],
    offerReceivedAt: {
        type: Date,
    },
    deadlineDate: {
        type: Date,
    },

    /**
     * Networking Contacts
     * Purpose: Store contacts at the company for networking and referrals
     * Fields: contacts[] (name, role, email, linkedIn, lastContactDate, notes)
     * Note: Embedded because contacts are bounded (few per application)
     *       and always viewed with the application
     */
    contacts: [{
        name: {
            type: String,
        },
        role: {
            type: String,
        },
        email: {
            type: String,
        },
        linkedIn: {
            type: String,
        },
        lastContactDate: {
            type: Date,
        },
        notes: {
            type: String,
        },
    }],

    /**
     * Notes & Prep
     * Purpose: Store interview prep, company research, and general notes
     * Fields: notes, resumeUsed
     */
    notes: {
        type: String,
        maxlength: 5000,
    },
    resumeUsed: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Resume',
        default: null,
    },

    /**
     * Follow-Up Reminders
     * Purpose: Track reminders to follow up on the application
     * Fields: followUpReminders[] (date, description, completed)
     * Note: Embedded because reminders are bounded (few per application)
     *       and always viewed with the application
     */
    followUpReminders: [{
        date: {
            type: Date,
        },
        description: {
            type: String,
        },
        completed: {
            type: Boolean,
            default: false,
        },
    }],

    /**
     * Metadata
     * Purpose: Track soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { userId: 1, status: 1, createdAt: -1 }  — "get my applications by status, newest first"
// { userId: 1, deadlineDate: 1 }            — "get my applications by upcoming deadline"
// { userId: 1, deletedAt: 1 }               — "get my non-deleted applications"
// ============================================================
applicationSchema.index({ userId: 1, status: 1, createdAt: -1 });  // "get my applications by status, newest first"
applicationSchema.index({ userId: 1, deadlineDate: 1 });            // "get my applications by upcoming deadline"
applicationSchema.index({ userId: 1, deletedAt: 1 });               // "get my non-deleted applications"

module.exports = mongoose.model('Application', applicationSchema);
