const mongoose = require('mongoose');

// ============================================================
// COMMENT SCHEMA
// Purpose: Define the structure of a Comment document in MongoDB
// Collection: comments
// Features: Polymorphic comments on notes/flashcard sets/tasks,
//           threaded replies, likes, denormalized user snapshots
// ============================================================
const commentSchema = new mongoose.Schema({
    /**
     * Polymorphic Target
     * Purpose: Link the comment to any content type (note, flashcardSet, task)
     * Fields: targetId, targetType
     * Note: targetId + targetType together identify what this comment is on
     */
    targetId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        index: true,
    },
    targetType: {
        type: String,
        enum: ['note', 'flashcardSet', 'task'],
        required: true,
        index: true,
    },

    /**
     * Author
     * Purpose: Link the comment to the user who wrote it
     * Fields: userId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Content
     * Purpose: Store the comment text
     * Fields: content
     */
    content: {
        type: String,
        required: true,
        maxlength: 2000,
    },

    /**
     * Threading
     * Purpose: Support nested/reply comments (optional for MVP)
     * Fields: parentId
     * Note: If parentId is null, this is a top-level comment
     */
    parentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Comment',
        default: null,
    },

    /**
     * Reactions
     * Purpose: Track which users have liked this comment
     * Fields: likes
     */
    likes: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }],

    /**
     * Denormalized User Info
     * Purpose: Cache author info at comment creation time for display performance
     * Fields: userSnapshot.username, firstName, lastName, avatarUrl
     * Note: Pre-save hook populates this on creation to avoid N+1 queries
     *       when displaying comment threads
     */
    userSnapshot: {
        username: {
            type: String,
        },
        firstName: {
            type: String,
        },
        lastName: {
            type: String,
        },
        avatarUrl: {
            type: String,
        },
    },

    /**
     * Metadata
     * Purpose: Track soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// PRE-SAVE HOOK
// Purpose: Runs automatically BEFORE a document is saved to the database
// Use: Snapshot the author's user info on creation so comment threads
//      can display usernames/avatars without querying the User collection
// When it runs: Only on new documents (not updates) — snapshot is a point-in-time cache
// ============================================================
commentSchema.pre('save', async function () {
    // Only snapshot on new comment creation, not on edits or likes
    if (!this.isNew) return;

    // Look up the author's current info from the User collection
    const User = mongoose.model('User');
    const user = await User.findById(this.userId).select('username firstName lastName avatarUrl');

    // Cache the author's info directly on the comment document
    if (user) {
        this.userSnapshot = {
            username: user.username,
            firstName: user.firstName,
            lastName: user.lastName,
            avatarUrl: user.avatarUrl,
        };
    }
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { targetId: 1, targetType: 1, createdAt: -1 } — "get comments on this note, newest first"
// { userId: 1, createdAt: -1 }                   — "get all comments by this user, newest first"
// { parentId: 1 }                                 — "get replies to this comment"
// ============================================================
commentSchema.index({ targetId: 1, targetType: 1, createdAt: -1 });  // "get comments on this note, newest first"
commentSchema.index({ userId: 1, createdAt: -1 });                   // "get all comments by this user, newest first"
commentSchema.index({ parentId: 1 });                                 // "get replies to this comment"

module.exports = mongoose.model('Comment', commentSchema);
