const mongoose = require('mongoose');

// ============================================================
// CONVERSATION SCHEMA
// Purpose: Define the structure of a Conversation document in MongoDB
// Collection: conversations
// Features: DM conversation containers, denormalized last message
//           for inbox performance, per-participant unread counts
// ============================================================
const conversationSchema = new mongoose.Schema({
    /**
     * Participants
     * Purpose: Store the two users in a DM conversation (always 2 for DMs)
     * Fields: participants
     */
    participants: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }],

    /**
     * Last Message (Denormalized)
     * Purpose: Cache the most recent message for inbox list performance
     * Fields: lastMessage.senderId, content, sentAt
     * Note: Denormalized so the inbox can display previews without
     *       querying the Message collection for every conversation
     */
    lastMessage: {
        senderId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        content: {
            type: String,
            maxlength: 200,
        },
        sentAt: {
            type: Date,
        },
    },

    /**
     * Unread Counts
     * Purpose: Track how many unread messages each participant has
     * Fields: unreadCounts[] (userId, count)
     * Note: Embedded because there are always exactly 2 entries (one per participant)
     */
    unreadCounts: [{
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        count: {
            type: Number,
            default: 0,
        },
    }],

    /**
     * Metadata
     * Purpose: Track soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { participants: 1, deletedAt: 1 }              — "find conversations for this user"
// { participants: 1, 'lastMessage.sentAt': -1 }  — "get user's inbox sorted by most recent message"
// ============================================================
conversationSchema.index({ participants: 1, deletedAt: 1 });              // "find conversations for this user"
conversationSchema.index({ participants: 1, 'lastMessage.sentAt': -1 });  // "get user's inbox sorted by most recent message"

module.exports = mongoose.model('Conversation', conversationSchema);
