const mongoose = require('mongoose');

// ============================================================
// FLASHCARD SET SCHEMA
// Purpose: Define the structure of a FlashcardSet document in MongoDB
// Collection: flashcardsets
// Features: Container for flashcard collections, linked to notes,
//           AI generation tracking, sharing, study metadata
// ============================================================
const flashcardSetSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link the set to a user and optionally to a source note
     * Fields: userId, noteId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },
    noteId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Note',
        index: true,
        default: null,
    },

    /**
     * Content
     * Purpose: Store the set's title and description
     * Fields: title, description
     */
    title: {
        type: String,
        maxlength: 200,
    },
    description: {
        type: String,
        maxlength: 1000,
    },

    /**
     * Study Metadata
     * Purpose: Track study activity and card count
     * Fields: totalCards, lastStudiedAt, studySessionCount
     */
    totalCards: {
        type: Number,
        default: 0,
    },
    lastStudiedAt: {
        type: Date,
    },
    studySessionCount: {
        type: Number,
        default: 0,
    },

    /**
     * Sharing
     * Purpose: Control who can see the flashcard set (per-set privacy)
     * Fields: visibility, sharedWith
     */
    visibility: {
        type: String,
        enum: ['private', 'friends', 'specific'],
        default: 'private',
    },
    sharedWith: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }],

    /**
     * AI Generation
     * Purpose: Track if the set was auto-generated from a note by AI
     * Fields: isAIGenerated, generatedAt
     */
    isAIGenerated: {
        type: Boolean,
        default: false,
    },
    generatedAt: {
        type: Date,
    },

    /**
     * Metadata
     * Purpose: Soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },
}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
// ============================================================
flashcardSetSchema.index({ userId: 1, deletedAt: 1, createdAt: -1 }); // "get my flashcard sets, newest first"
flashcardSetSchema.index({ noteId: 1, deletedAt: 1 });                 // "get all sets linked to this note"

// ============================================================
// VIRTUALS
// Purpose: Computed properties that DON'T get stored in the database
// They're calculated on-the-fly when you access them (like a getter)
// ============================================================

/**
 * flashcards
 * Purpose: Populate all Flashcards belonging to this set without storing them on the set
 * Usage: set.populate('flashcards') → array of Flashcard documents
 * Note: Requires .populate('flashcards') in the query to actually load the data
 */
flashcardSetSchema.virtual('flashcards', {
    ref: 'Flashcard',
    localField: '_id',
    foreignField: 'setId',
});

module.exports = mongoose.model('FlashcardSet', flashcardSetSchema);
