const mongoose = require('mongoose');

// ============================================================
// FLASHCARD SCHEMA
// Purpose: Define the structure of a Flashcard document in MongoDB
// Collection: flashcards
// Features: Individual flashcard pairs, per-user study progress,
//           ordering within sets, supports shared sets
// ============================================================
const flashcardSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link the flashcard to its parent FlashcardSet
     * Fields: setId
     */
    setId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'FlashcardSet',
        required: true,
        index: true,
    },

    /**
     * Content
     * Purpose: Store the question/term and answer/definition
     * Fields: front, back
     */
    front: {
        type: String,
        required: true,
    },
    back: {
        type: String,
        required: true,
    },

    /**
     * User Progress
     * Purpose: Track each user's study performance on this card
     * Fields: userProgress[].userId, lastStudied, correctCount, incorrectCount, confidence
     * Note: This is an ARRAY because shared sets have multiple users studying the same card
     *       Each user gets their own progress entry
     */
    userProgress: [{
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        lastStudied: {
            type: Date,
        },
        correctCount: {
            type: Number,
            default: 0,
        },
        incorrectCount: {
            type: Number,
            default: 0,
        },
        confidence: {
            type: String,
            enum: ['low', 'medium', 'high'],
        },
    }],

    /**
     * Order
     * Purpose: Position of this card within its set (for consistent ordering)
     * Fields: order
     */
    order: {
        type: Number,
    },

    /**
     * Metadata
     * Purpose: Soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },
}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
// ============================================================
flashcardSchema.index({ setId: 1, deletedAt: 1, order: 1 });    // "get all cards in this set, in order"
flashcardSchema.index({ 'userProgress.userId': 1 });              // "get all cards this user has studied"

module.exports = mongoose.model('Flashcard', flashcardSchema);
