const mongoose = require('mongoose');

// ============================================================
// FRIENDSHIP SCHEMA
// Purpose: Define the structure of a Friendship document in MongoDB
// Collection: friendships
// Features: Friend requests, friend relationships, blocking,
//           unordered user pairs (user1 < user2) to prevent duplicates
// ============================================================
const friendshipSchema = new mongoose.Schema({
    /**
     * Unordered Relationship
     * Purpose: Store the two users in a friendship (user1 < user2 for consistency)
     * Fields: user1, user2
     * Note: Pre-save hook ensures user1 < user2 to prevent duplicate friendships
     */
    user1: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },
    user2: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Request Flow
     * Purpose: Track who sent the friend request and the current status
     * Fields: requestedBy, status
     */
    requestedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    status: {
        type: String,
        enum: ['pending', 'accepted', 'rejected', 'blocked'],
        default: 'pending',
        index: true,
    },

    /**
     * Metadata
     * Purpose: Track request/response timing and soft deletes
     * Fields: requestedAt, respondedAt, deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    requestedAt: {
        type: Date,
    },
    respondedAt: {
        type: Date,
    },
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// PRE-SAVE HOOK
// Purpose: Runs automatically BEFORE a document is saved to the database
// Use: Ensure user1 < user2 for consistent ordering (prevents duplicate friendships)
// When it runs: Every time .save() is called — but only acts if user1/user2 changed
//
// Steps:
// 1. Check if user1 or user2 was modified (skip on status updates, etc.)
// 2. Compare user1 and user2 ObjectId strings
// 3. If user1 > user2, swap them so the smaller ID is always user1
// ============================================================
friendshipSchema.pre('save', function () {
    // Skip if user1/user2 weren't changed (e.g. just a status update)
    if (!this.isModified('user1') && !this.isModified('user2')) return;

    // Compare as strings — if user1 is "bigger", swap them
    // Example: user1 = "67b3..." and user2 = "67a1..."
    //          "67b3" > "67a1" is true, so we swap → user1 = "67a1", user2 = "67b3"
    if (this.user1.toString() > this.user2.toString()) {
        const temp = this.user1;
        this.user1 = this.user2;
        this.user2 = temp;
    }
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { user1: 1, user2: 1 }        — unique compound: prevent duplicate friendships (A↔B)
// { user1: 1, status: 1 }       — "get user1's friends by status"
// { user2: 1, status: 1 }       — "get user2's friends by status"
// { requestedBy: 1, status: 1 } — "get requests sent by a user"
// ============================================================
friendshipSchema.index({ user1: 1, user2: 1 }, { unique: true });  // prevent duplicate friendships
friendshipSchema.index({ user1: 1, status: 1 });                   // "get user1's friends by status"
friendshipSchema.index({ user2: 1, status: 1 });                   // "get user2's friends by status"
friendshipSchema.index({ requestedBy: 1, status: 1 });             // "get requests sent by a user"

module.exports = mongoose.model('Friendship', friendshipSchema);
