const mongoose = require('mongoose');

// ============================================================
// MESSAGE SCHEMA
// Purpose: Define the structure of a Message document in MongoDB
// Collection: messages
// Features: Individual messages within conversations, read receipts,
//           offline sync support with client timestamps
// ============================================================
const messageSchema = new mongoose.Schema({
    /**
     * Conversation Link
     * Purpose: Link the message to its parent conversation
     * Fields: conversationId
     */
    conversationId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Conversation',
        required: true,
        index: true,
    },

    /**
     * Sender
     * Purpose: Link the message to the user who sent it
     * Fields: senderId
     */
    senderId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Content
     * Purpose: Store the message text
     * Fields: content
     */
    content: {
        type: String,
        required: true,
        maxlength: 5000,
    },

    /**
     * Read Status
     * Purpose: Track which participants have read this message and when
     * Fields: readBy[] (userId, readAt)
     * Note: Embedded because there are at most 2 entries (one per DM participant)
     */
    readBy: [{
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        readAt: {
            type: Date,
        },
    }],

    /**
     * Offline Sync
     * Purpose: Support offline messaging by tracking client-side timestamps
     *          and sync status for eventual consistency
     * Fields: clientTimestamp, syncStatus
     */
    clientTimestamp: {
        type: Date,
    },
    syncStatus: {
        type: String,
        enum: ['pending', 'synced', 'failed'],
        default: 'synced',
    },

    /**
     * Metadata
     * Purpose: Track soft deletes
     * Fields: deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { conversationId: 1, createdAt: -1 } — "get messages in a conversation, newest first"
// { senderId: 1, createdAt: -1 }       — "get all messages sent by a user, newest first"
// ============================================================
messageSchema.index({ conversationId: 1, createdAt: -1 });  // "get messages in a conversation, newest first"
messageSchema.index({ senderId: 1, createdAt: -1 });        // "get all messages sent by a user, newest first"

module.exports = mongoose.model('Message', messageSchema);
