const mongoose = require('mongoose');

// ============================================================
// NOTE SCHEMA
// Purpose: Define the structure of a Note document in MongoDB
// Collection: notes
// Features: Google Docs imports, native notes, content management,
//           sharing/visibility, embedded AI summaries, organization
// ============================================================
const noteSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link every note to the user who created it
     * Fields: userId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Content
     * Purpose: Store the note's title, body, and format type
     * Fields: title, content, contentType
     */
    title: {
        type: String,
        maxlength: 200,
    },
    content: {
        type: String,
    },
    contentType: {
        type: String,
        enum: ['html', 'markdown', 'plain'],
    },

    /**
     * Google Docs Integration
     * Purpose: Link to a Google Doc for syncing content
     * Fields: googleDocId, googleDocUrl, lastSyncedAt
     */
    googleDocId: {
        type: String,
        unique: true,
        sparse: true,
    },
    googleDocUrl: {
        type: String,
    },
    lastSyncedAt: {
        type: Date,
    },

    /**
     * Organization
     * Purpose: Categorize and organize notes with tags, subjects, and folders
     * Fields: tags, subject, folder
     */
    tags: [{
        type: String,
        lowercase: true,
    }],
    subject: {
        type: String,
    },
    folder: {
        type: String,
        default: 'default',
    },

    /**
     * Sharing
     * Purpose: Control who can see the note (per-note privacy)
     * Fields: visibility, sharedWith
     */
    visibility: {
        type: String,
        enum: ['private', 'friends', 'specific'],
        default: 'private',
        index: true,
    },
    sharedWith: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }],

    /**
     * Embedded AI Summary
     * Purpose: Store AI-generated summaries directly on the note (no separate collection)
     * Fields: summary.quickSummary, summary.detailedSummary, summary.generatedAt,
     *         summary.model, summary.tokenCount
     */
    summary: {
        quickSummary: {
            type: String,
        },
        detailedSummary: {
            type: String,
        },
        generatedAt: {
            type: Date,
        },
        model: {
            type: String,
        },
        tokenCount: {
            type: Number,
        },
    },

    /**
     * Denormalized Flags
     * Purpose: Quick lookup flags to avoid querying other collections
     * Fields: hasFlashcards
     */
    hasFlashcards: {
        type: Boolean,
        default: false,
    },

    /**
     * Metadata
     * Purpose: Track note status, engagement, and soft deletes
     * Fields: isPinned, viewCount, lastViewedAt, deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    isPinned: {
        type: Boolean,
        default: false,
    },
    viewCount: {
        type: Number,
        default: 0,
    },
    lastViewedAt: {
        type: Date,
    },
    deletedAt: {
        type: Date,
        default: null,
    },
}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// Note: unique fields (googleDocId) already have indexes from the schema
// These compound indexes optimize queries that filter by BOTH fields at once
// ============================================================
noteSchema.index({ userId: 1, deletedAt: 1, createdAt: -1 }); // "get my notes, newest first, excluding deleted"
noteSchema.index({ userId: 1, tags: 1 });                      // "get my notes filtered by tag"
noteSchema.index({ userId: 1, subject: 1 });                   // "get my notes filtered by subject"
// googleDocId index already created by unique: true + sparse: true in schema
noteSchema.index({ visibility: 1, deletedAt: 1 });             // "get all public/friends notes" (social feed)

// ============================================================
// VIRTUALS
// Purpose: Computed properties that DON'T get stored in the database
// They're calculated on-the-fly when you access them (like a getter)
// ============================================================

/**
 * hasSummary
 * Purpose: Quick check if an AI summary has been generated for this note
 * Usage: note.hasSummary → true/false
 */
noteSchema.virtual('hasSummary').get(function () {
    return !!this.summary?.quickSummary;
});

/**
 * flashcardSets
 * Purpose: Populate all FlashcardSets linked to this note without storing them on the Note
 * Usage: note.populate('flashcardSets') → array of FlashcardSet documents
 * Note: Requires .populate('flashcardSets') in the query to actually load the data
 */
noteSchema.virtual('flashcardSets', {
    ref: 'FlashcardSet',        // The model to populate from
    localField: '_id',          // Match Note._id...
    foreignField: 'noteId',     // ...against FlashcardSet.noteId
});

/**
 * commentsCount
 * Purpose: Get the number of comments on this note without storing a counter
 * Usage: note.populate('commentsCount') → number
 * Note: Requires .populate('commentsCount') in the query to actually load the count
 */
noteSchema.virtual('commentsCount', {
    ref: 'Comment',             // The model to count from
    localField: '_id',          // Match Note._id...
    foreignField: 'noteId',     // ...against Comment.noteId
    count: true,                // Return count instead of documents
});

module.exports = mongoose.model('Note', noteSchema);