const mongoose = require('mongoose');

// ============================================================
// RESUME SCHEMA
// Purpose: Define the structure of a Resume document in MongoDB
// Collection: resumes
// Features: Resume file storage, version management, embedded AI feedback,
//           cached extracted text for instant AI processing
// ============================================================
const resumeSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link the resume to the user who uploaded it
     * Fields: userId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * File Info
     * Purpose: Store the uploaded resume file details (hosted on Cloudinary)
     * Fields: fileName, fileUrl, fileSize, mimeType
     */
    fileName: {
        type: String,
        required: true,
    },
    fileUrl: {
        type: String,
        required: true,
    },
    fileSize: {
        type: Number,
    },
    mimeType: {
        type: String,
        default: 'application/pdf',
    },

    /**
     * Version Management
     * Purpose: Track different resume versions and their target roles
     * Fields: version, targetRole
     */
    version: {
        type: String,
    },
    targetRole: {
        type: String,
    },

    /**
     * Embedded AI Feedback
     * Purpose: Store AI-generated resume feedback directly on the document
     * Fields: feedback[] (overallScore, strengths, improvements, sections, keywordOptimization, model, generatedAt)
     * Note: Feedback is 1:few (a user might regenerate 2-3 times per resume version).
     *       It's always viewed with the resume. Embedding eliminates a whole collection
     *       and avoids extra queries.
     */
    feedback: [{
        overallScore: {
            type: Number,
            min: 0,
            max: 100,
        },
        strengths: [{
            type: String,
        }],
        improvements: [{
            type: String,
        }],

        sections: [{
            name: {
                type: String,
            },
            feedback: {
                type: String,
            },
            score: {
                type: Number,
                min: 0,
                max: 100,
            },
        }],

        keywordOptimization: {
            presentKeywords: [{
                type: String,
            }],
            missingKeywords: [{
                type: String,
            }],
        },

        model: {
            type: String,
        },
        generatedAt: {
            type: Date,
        },
    }],

    /**
     * Extracted Text
     * Purpose: Cache the parsed PDF text on upload so AI feedback is instant
     * Fields: extractedText
     * Note: select: false prevents loading this large field on normal queries.
     *       PDF text extraction happens once on upload (using pdf-parse).
     *       Storing the result means AI feedback requests don't need to re-parse the PDF.
     */
    extractedText: {
        type: String,
        select: false,
    },

    /**
     * Metadata
     * Purpose: Track upload time and soft deletes
     * Fields: uploadedAt, deletedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    uploadedAt: {
        type: Date,
    },
    deletedAt: {
        type: Date,
        default: null,
    },

}, {
    timestamps: true,
});

// ============================================================
// VIRTUALS
// Purpose: Computed properties that DON'T get stored in the database
// They're calculated on-the-fly when you access them (like a getter)
// ============================================================

/**
 * hasFeedback
 * Purpose: Quick check if any AI feedback has been generated for this resume
 * Usage: resume.hasFeedback → true/false
 */
resumeSchema.virtual('hasFeedback').get(function () {
    return this.feedback.length > 0;
});

/**
 * latestFeedback
 * Purpose: Get the most recent AI feedback without manually indexing the array
 * Usage: resume.latestFeedback → { overallScore, strengths, ... } or undefined
 */
resumeSchema.virtual('latestFeedback').get(function () {
    return this.feedback[this.feedback.length - 1];
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { userId: 1, deletedAt: 1, createdAt: -1 } — "get my resumes, newest first, excluding deleted"
// ============================================================
resumeSchema.index({ userId: 1, deletedAt: 1, createdAt: -1 });  // "get my resumes, newest first"

module.exports = mongoose.model('Resume', resumeSchema);
