const mongoose = require('mongoose');

// ============================================================
// SYNC QUEUE SCHEMA
// Purpose: Define the structure of a SyncQueue document in MongoDB
// Collection: syncqueues
// Features: Queue offline operations for server sync, track operation
//           status, store flexible payloads with Schema.Types.Mixed
// ============================================================
const syncQueueSchema = new mongoose.Schema({
    /**
     * Ownership
     * Purpose: Link the queued operation to the user who created it
     * Fields: userId
     */
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
    },

    /**
     * Operation Details
     * Purpose: Describe what offline operation needs to be synced
     * Fields: operation, collection, documentId
     */
    operation: {
        type: String,
        enum: ['create', 'update', 'delete'],
        required: true,
    },
    collection: {
        type: String,
        enum: ['notes', 'tasks', 'flashcards', 'messages'],
        required: true,
    },
    documentId: {
        type: mongoose.Schema.Types.ObjectId,
    },

    /**
     * Data
     * Purpose: Store the operation payload (flexible structure per operation type)
     * Fields: data
     * Note: Schema.Types.Mixed allows any JSON structure — each operation type
     *       (create/update/delete) may have a different payload shape
     */
    data: {
        type: mongoose.Schema.Types.Mixed,
    },

    /**
     * Status
     * Purpose: Track the sync operation through its lifecycle
     * Fields: status, errorMessage
     */
    status: {
        type: String,
        enum: ['pending', 'processing', 'completed', 'failed'],
        default: 'pending',
        index: true,
    },
    errorMessage: {
        type: String,
    },

    /**
     * Timestamps
     * Purpose: Track when the operation was created on the client and processed on the server
     * Fields: clientTimestamp, processedAt
     * Note: createdAt/updatedAt are auto-generated by timestamps option
     */
    clientTimestamp: {
        type: Date,
    },
    processedAt: {
        type: Date,
    },

}, {
    timestamps: true,
});

// ============================================================
// INDEXES
// Purpose: Speed up common queries by telling MongoDB which fields to pre-sort
// These compound indexes optimize queries that filter by BOTH fields at once
//
// { userId: 1, status: 1, clientTimestamp: 1 } — "get a user's pending operations in order"
// { status: 1, createdAt: 1 }                  — "process oldest pending operations first"
// ============================================================
syncQueueSchema.index({ userId: 1, status: 1, clientTimestamp: 1 });  // "get a user's pending operations in order"
syncQueueSchema.index({ status: 1, createdAt: 1 });                   // "process oldest pending operations first"

module.exports = mongoose.model('SyncQueue', syncQueueSchema);
